apiVersion: apps/v1
kind: Deployment
metadata:
    name: flask-demo
    labels:
        app: flask-demo
spec:
    replicas: 2
    selector:
        matchLabels:
            app: flask-demo
    template:
        metadata:
            labels:
                app: flask-demo
        spec:
            containers:
            -  image: devopswithsam/argodemo:24
               name: flask-demo
